name: "Lint"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext lint"
        uses: kewisch/action-web-ext@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          cmd: lint
          source: .
          channel: listed
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock", ".github" ]'

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cmd: build
          filename: "{name}-{version}.xpi"
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          ignoreFiles: '[ "package.json","package-lock.json","yarn.lock", ".github" ]'

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: target.xpi
          path: "${{ steps.web-ext-build.outputs.target }}"